name: get-gh-stats

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  get-svg:
    runs-on: ubuntu-latest
    steps:
      - name: fetch-svg
        id: svg
        run: curl --output "mdb.svg" "https://github-readme-stats.vercel.app/api\?username\=mdb\&count_private\=true\&include_all_commits\=true\&custom_title\=GitHub%20Stats"
      - name: upload-svg
        uses: actions/upload-artifact@v2
        with:
          name: svg
          path: |
            *.svg
          retention-days: 1

  publish-svg-to-gh-pages:
    needs: get-svg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: download-svg
        uses: actions/download-artifact@v2
        with:
          name: svg
          path: svg
      - name: publish-svg-to-gh-pages
        uses: mikeal/publish-to-github-action@923d6a6f64c943c0f82f81180c4a84d8e0edaa3e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: gh-pages
